version: '3'
services:
  exchange_rate_service:
    build: 
      context: .
      dockerfile: exchange_rate_service/Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./.env

  conversion_service:
    build: 
      context: .
      dockerfile: conversion_service/Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - exchange_rate_service

  frontend_service:
    build: 
      context: .
      dockerfile: frontend_service/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - conversion_service
