name: CD APP

on:
    workflow_run:
        workflows: ["Docker Image CI"]
        types:
            - completed

jobs:

    build:

        runs-on: self-hosted

        steps:
            - name: Pull Docker image
              run: docker pull edwinallauca/foreign_exchange:latest
            - name: Delete Old Docker Container
              run: docker rm -f foreign_exchange-container || true
            - name: Run Docker Container
              run: docker run -d -p 5000:5000 --name foreign_exchange-container edwinallauca/foreign_exchange

